# End To End Analysis

## Data Cleaning

#### importing the data

In [23]:
import pandas as pd
df = pd.read_excel("Sample data (1).xlsx")

#### Display first five record

In [5]:
df.head()

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Month Name,Year
0,Government,Germany,Carretera,NaN,1513.0,3,350,529550.0,0.0,529550.0,393380.0,136170.0,2014-12-01,12,December,2014
1,Government,Germany,Paseo,NaN,1006.0,10,350,352100.0,0.0,352100.0,261560.0,90540.0,2014-06-01,6,June,2014
2,Government,Canada,Paseo,NaN,1725.0,10,350,603750.0,0.0,603750.0,448500.0,155250.0,2013-11-01,11,November,2013
3,Government,Germany,Paseo,NaN,1513.0,10,350,529550.0,0.0,529550.0,393380.0,136170.0,2014-12-01,12,December,2014
4,Government,Germany,Velo,NaN,1006.0,120,350,352100.0,0.0,352100.0,261560.0,90540.0,2014-06-01,6,June,2014

#### Check the Data Structure

##### =>There are 700 rows and 16 columns in the given data set

In [7]:
df.shape

(700, 16)

#### Display columns

In [9]:
df.columns

Index(['Segment', 'Country', 'Product', 'Discount Band', 'Units Sold',
       'Manufacturing Price', 'Sale Price', 'Gross Sales', 'Discounts',
       ' Sales', 'COGS', 'Profit', 'Date', 'Month Number', 'Month Name',
       'Year'],
      dtype='object')

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Segment              700 non-null    object
 1   Country              700 non-null    object
 2   Product              700 non-null    object
 3   Discount Band        647 non-null    object
 4   Units Sold           700 non-null    float64
 5   Manufacturing Price  700 non-null    int64
 6   Sale Price           700 non-null    int64
 7   Gross Sales          700 non-null    float64
 8   Discounts            700 non-null    float64
 9    Sales               700 non-null    float64
 10  COGS                 700 non-null    float64
 11  Profit               700 non-null    float64
 12  Date                 700 non-null    datetime64[ns]
 13  Month Number         700 non-null    int64
 14  Month Name           700 non-null    object
 15  Year                 700 non-null    int64
dtypes: datetime64[ns](1), float64(6), int64(4), object(5)
memory usage: 87.6+ KB

#### Check null values

##### =>There are 53 null values in Discount Band column

In [24]:
df.isnull().sum()

Segment                 0
Country                 0
Product                 0
Discount Band          53
Units Sold              0
Manufacturing Price     0
Sale Price              0
Gross Sales             0
Discounts               0
 Sales                  0
COGS                    0
Profit                  0
Date                    0
Month Number            0
Month Name              0
Year                    0
dtype: int64

#### Check duplicates

##### => There are no duplicate values in the data

In [12]:
df.duplicated().sum()

np.int64(0)

#### Display first 10 records in the data containing null values in Discount Band column

In [13]:
df[df["Discount Band"].isnull()].head(10)

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Month Name,Year
0,Government,Germany,Carretera,NaN,1513.0,3,350,529550.0,0.0,529550.0,393380.0,136170.0,2014-12-01,12,December,2014
1,Government,Germany,Paseo,NaN,1006.0,10,350,352100.0,0.0,352100.0,261560.0,90540.0,2014-06-01,6,June,2014
2,Government,Canada,Paseo,NaN,1725.0,10,350,603750.0,0.0,603750.0,448500.0,155250.0,2013-11-01,11,November,2013
3,Government,Germany,Paseo,NaN,1513.0,10,350,529550.0,0.0,529550.0,393380.0,136170.0,2014-12-01,12,December,2014
4,Government,Germany,Velo,NaN,1006.0,120,350,352100.0,0.0,352100.0,261560.0,90540.0,2014-06-01,6,June,2014
5,Government,France,VTT,NaN,1527.0,250,350,534450.0,0.0,534450.0,397020.0,137430.0,2013-09-01,9,September,2013
6,Government,France,Amarilla,NaN,2750.0,260,350,962500.0,0.0,962500.0,715000.0,247500.0,2014-02-01,2,February,2014
100,Government,Canada,Carretera,NaN,1618.5,3,20,32370.0,0.0,32370.0,16185.0,16185.0,2014-01-01,1,January,2014
101,Government,Germany,Carretera,NaN,1321.0,3,20,26420.0,0.0,26420.0,13210.0,13210.0,2014-01-01,1,January,2014
102,Government,France,Montana,NaN,1899.0,5,20,37980.0,0.0,37980.0,18990.0,18990.0,2014-06-01,6,June,2014

#### Fill the missing Discount Band values

In [14]:
df["Discount Band"] = df["Discount Band"].fillna("No Discount")

In [15]:
df.duplicated().sum()

np.int64(0)

#### Check the Discount Band categories

In [16]:
df["Discount Band"].value_counts()

Discount Band
High           245
Medium         242
Low            160
No Discount     53
Name: count, dtype: int64

#### Check leading spaces

In [19]:
df.columns = df.columns.str.strip()

In [20]:
df.columns

Index(['Segment', 'Country', 'Product', 'Discount Band', 'Units Sold',
       'Manufacturing Price', 'Sale Price', 'Gross Sales', 'Discounts',
       'Sales', 'COGS', 'Profit', 'Date', 'Month Number', 'Month Name',
       'Year'],
      dtype='object')

In [21]:
df.dtypes

Segment                        object
Country                        object
Product                        object
Discount Band                  object
Units Sold                    float64
Manufacturing Price             int64
Sale Price                      int64
Gross Sales                   float64
Discounts                     float64
Sales                         float64
COGS                          float64
Profit                        float64
Date                   datetime64[ns]
Month Number                    int64
Month Name                     object
Year                            int64
dtype: object

#### Save Cleaned Data

In [22]:
df.to_csv("cleaned_data.csv", index=False)
df.head()

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Month Name,Year
0,Government,Germany,Carretera,No Discount,1513.0,3,350,529550.0,0.0,529550.0,393380.0,136170.0,2014-12-01,12,December,2014
1,Government,Germany,Paseo,No Discount,1006.0,10,350,352100.0,0.0,352100.0,261560.0,90540.0,2014-06-01,6,June,2014
2,Government,Canada,Paseo,No Discount,1725.0,10,350,603750.0,0.0,603750.0,448500.0,155250.0,2013-11-01,11,November,2013
3,Government,Germany,Paseo,No Discount,1513.0,10,350,529550.0,0.0,529550.0,393380.0,136170.0,2014-12-01,12,December,2014
4,Government,Germany,Velo,No Discount,1006.0,120,350,352100.0,0.0,352100.0,261560.0,90540.0,2014-06-01,6,June,2014

In [3]:
import pandas as pd

df = pd.read_csv("cleaned_data.csv")
df["Date"] = pd.to_datetime(df["Date"])

df.head()

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Month Name,Year
0,Government,Germany,Carretera,No Discount,1513.0,3,350,529550.0,0.0,529550.0,393380.0,136170.0,2014-12-01,12,December,2014
1,Government,Germany,Paseo,No Discount,1006.0,10,350,352100.0,0.0,352100.0,261560.0,90540.0,2014-06-01,6,June,2014
2,Government,Canada,Paseo,No Discount,1725.0,10,350,603750.0,0.0,603750.0,448500.0,155250.0,2013-11-01,11,November,2013
3,Government,Germany,Paseo,No Discount,1513.0,10,350,529550.0,0.0,529550.0,393380.0,136170.0,2014-12-01,12,December,2014
4,Government,Germany,Velo,No Discount,1006.0,120,350,352100.0,0.0,352100.0,261560.0,90540.0,2014-06-01,6,June,2014

In [4]:
df.shape

(700, 16)

#### Total Sales

In [5]:
df["Sales"].sum()

np.float64(118726350.25999999)

#### Total Profit

In [6]:
df["Profit"].sum()

np.float64(16893702.26)

#### Average sales

In [7]:
df["Sales"].mean()

np.float64(169609.07179999998)

#### Average profit

In [8]:
df["Profit"].mean()

np.float64(24133.860371428575)

#### Records having highest and lowest profit

In [9]:
df.loc[df["Profit"].idxmax()]

Segment                              Government
Country                United States of America
Product                                   Paseo
Discount Band                               Low
Units Sold                               3450.0
Manufacturing Price                          10
Sale Price                                  350
Gross Sales                           1207500.0
Discounts                               48300.0
Sales                                 1159200.0
COGS                                   897000.0
Profit                                 262200.0
Date                        2014-07-01 00:00:00
Month Number                                  7
Month Name                                 July
Year                                       2014
Name: 24, dtype: object

In [10]:
df.loc[df["Profit"].idxmin()]

Segment                         Enterprise
Country                             Canada
Product                                VTT
Discount Band                         High
Units Sold                          2954.0
Manufacturing Price                    250
Sale Price                             125
Gross Sales                       369250.0
Discounts                          55387.5
Sales                             313862.5
COGS                              354480.0
Profit                            -40617.5
Date                   2013-11-01 00:00:00
Month Number                            11
Month Name                        November
Year                                  2013
Name: 581, dtype: object

#### Product with highest total Sales

In [11]:
product_sales = df.groupby("Product")["Sales"].sum()
product_sales.sort_values(ascending=False)

Product
Paseo        3.301114e+07
VTT          2.051192e+07
Velo         1.825006e+07
Amarilla     1.774712e+07
Montana      1.539080e+07
Carretera    1.381531e+07
Name: Sales, dtype: float64

#### Products with highest sales

In [12]:
df.groupby("Product")["Sales"].sum().idxmax()

'Paseo'

#### Product generating the highest total Profit

In [13]:
df.groupby("Product")["Profit"].sum().sort_values(ascending=False)

Product
Paseo        4797437.950
VTT          3034608.020
Amarilla     2814104.060
Velo         2305992.465
Montana      2114754.880
Carretera    1826804.885
Name: Profit, dtype: float64

#### Products with highest profit

In [15]:
df.groupby("Product")["Profit"].sum().idxmax()

'Paseo'

#### Products with highest unit sold

In [16]:
df.groupby("Product")["Units Sold"].sum().sort_values(ascending=False)

Product
Paseo        338239.5
VTT          168783.0
Velo         162424.5
Amarilla     155315.0
Montana      154198.0
Carretera    146846.0
Name: Units Sold, dtype: float64

#### Country with highest total Sales

In [17]:
df.groupby("Country")["Sales"].sum().sort_values(ascending=False)

Country
United States of America    2.502983e+07
Canada                      2.488765e+07
France                      2.435417e+07
Germany                     2.350534e+07
Mexico                      2.094935e+07
Name: Sales, dtype: float64

#### Country with highest Total Profit

In [18]:
df.groupby("Country")["Profit"].sum().sort_values(ascending=False)

Country
France                      3781020.780
Germany                     3680388.820
Canada                      3529228.885
United States of America    2995540.665
Mexico                      2907523.110
Name: Profit, dtype: float64

#### Country with Highest Unit Sold

In [20]:
df.groupby("Country")["Units Sold"].sum().sort_values(ascending=False)

Country
Canada                      247428.5
France                      240931.0
United States of America    232627.5
Mexico                      203325.0
Germany                     201494.0
Name: Units Sold, dtype: float64

#### Segment generates Highest Total sales

In [21]:
df.groupby("Segment")["Sales"].sum().sort_values(ascending=False)

Segment
Government          5.250426e+07
Small Business      4.242792e+07
Enterprise          1.961169e+07
Midmarket           2.381883e+06
Channel Partners    1.800594e+06
Name: Sales, dtype: float64

#### Segment generates Highest Total Profit

In [22]:
df.groupby("Segment")["Profit"].sum().sort_values(ascending=False)

Segment
Government          1.138817e+07
Small Business      4.143168e+06
Channel Partners    1.316803e+06
Midmarket           6.601031e+05
Enterprise         -6.145456e+05
Name: Profit, dtype: float64

#### Relation of Discount Band to Sales and Profit

In [23]:
df.groupby("Discount Band")[["Sales", "Profit", "Discounts"]].sum().sort_values(
    by="Sales", ascending=False
)

                      Sales       Profit    Discounts
Discount Band
Medium         3.878043e+07  5579522.835  3002546.165
High           3.737249e+07  3388866.725  5317026.275
Low            3.462978e+07  6188857.700   885675.800
No Discount    7.943654e+06  1736455.000        0.000

#### Year and Month having Highest Sales and Profit

In [24]:
df.groupby("Year")["Sales"].sum().sort_values(ascending=False)

Year
2014    92311094.75
2013    26415255.51
Name: Sales, dtype: float64

In [25]:
df.groupby("Year")["Profit"].sum().sort_values(ascending=False)

Year
2014    13015237.75
2013     3878464.51
Name: Profit, dtype: float64